version: "3.7"
services:

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - backend

  sw-service:
    container_name: sw-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4567:4567
    restart: always
    env_file:
      - ./.env
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - backend

networks:
  backend:
    driver: bridge